import os, sys
from PIL import Image
import glob

width = 48
height = 48
# open an image file (.bmp,.jpg,.png,.gif) you have in the working folder
c=0
for img in glob.glob("/*.png")
    c=c+1
    im1 = Image.open(img)
    # adjust width and height to your needs
    
    # use one of these filter options to resize the image
    imout1 = im1.resize((width, height), Image.BILINEAR)     # linear interpolation in a 2x2 environment
    ext = ".png"

    imout1.save("BILINEAR"+c+ " "+ ext)




# optional image viewer ...
# image viewer  i_view32.exe   free download from:  http://www.irfanview.com/
# avoids the many huge bitmap files generated by PIL's show()
#import os
#os.system("d:/python24/i_view32.exe %s" % "BILINEAR.jpg")

'''img1 = Image.open('1a.png').convert('L')
img2 = Image.open('2b.png').convert('L')

img1.save('greyscale1.png')
img2.save('greyscale2.png')'''